# Generated by Django 5.2.10 on 2026-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=15),
        ),
    ]
