# Generated by Django 5.2.10 on 2026-01-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesbill_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbill',
            name='room_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
