# Generated by Django 5.2.10 on 2026-01-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_salesbill_payment_method_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='price',
        ),
    ]
